const toMs = require("ms")
module.exports = async(sock, m, prefix, command) => {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 DETIK`, rowId: `${prefix + command} seconds ${toMs("1seconds")}`, description: `${command.toUpperCase()} 1 DETIK`},
{title: `2 DETIK`, rowId: `${prefix + command} seconds ${toMs("2seconds")}`, description: `${command.toUpperCase()} 2 DETIK`},
{title: `3 DETIK`, rowId: `${prefix + command} seconds ${toMs("3seconds")}`, description: `${command.toUpperCase()} 3 DETIK`},
{title: `4 DETIK`, rowId: `${prefix + command} seconds ${toMs("4seconds")}`, description: `${command.toUpperCase()} 4 DETIK`},
{title: `5 DETIK`, rowId: `${prefix + command} seconds ${toMs("5seconds")}`, description: `${command.toUpperCase()} 5 DETIK`},
{title: `6 DETIK`, rowId: `${prefix + command} seconds ${toMs("6seconds")}`, description: `${command.toUpperCase()} 6 DETIK`},
{title: `7 DETIK`, rowId: `${prefix + command} seconds ${toMs("7seconds")}`, description: `${command.toUpperCase()} 7 DETIK`},
{title: `8 DETIK`, rowId: `${prefix + command} seconds ${toMs("8seconds")}`, description: `${command.toUpperCase()} 8 DETIK`},
{title: `9 DETIK`, rowId: `${prefix + command} seconds ${toMs("9seconds")}`, description: `${command.toUpperCase()} 9 DETIK`},
{title: `10 DETIK`, rowId: `${prefix + command} seconds ${toMs("10seconds")}`, description: `${command.toUpperCase()} 10 DETIK`},
{title: `11 DETIK`, rowId: `${prefix + command} seconds ${toMs("11seconds")}`, description: `${command.toUpperCase()} 11 DETIK`},
{title: `12 DETIK`, rowId: `${prefix + command} seconds ${toMs("12seconds")}`, description: `${command.toUpperCase()} 12 DETIK`},
{title: `13 DETIK`, rowId: `${prefix + command} seconds ${toMs("13seconds")}`, description: `${command.toUpperCase()} 13 DETIK`},
{title: `14 DETIK`, rowId: `${prefix + command} seconds ${toMs("14seconds")}`, description: `${command.toUpperCase()} 14 DETIK`},
{title: `15 DETIK`, rowId: `${prefix + command} seconds ${toMs("15seconds")}`, description: `${command.toUpperCase()} 15 DETIK`},
{title: `16 DETIK`, rowId: `${prefix + command} seconds ${toMs("16seconds")}`, description: `${command.toUpperCase()} 16 DETIK`},
{title: `17 DETIK`, rowId: `${prefix + command} seconds ${toMs("17seconds")}`, description: `${command.toUpperCase()} 17 DETIK`},
{title: `18 DETIK`, rowId: `${prefix + command} seconds ${toMs("18seconds")}`, description: `${command.toUpperCase()} 18 DETIK`},
{title: `19 DETIK`, rowId: `${prefix + command} seconds ${toMs("19seconds")}`, description: `${command.toUpperCase()} 19 DETIK`},
{title: `20 DETIK`, rowId: `${prefix + command} seconds ${toMs("20seconds")}`, description: `${command.toUpperCase()} 20 DETIK`},
{title: `21 DETIK`, rowId: `${prefix + command} seconds ${toMs("21seconds")}`, description: `${command.toUpperCase()} 21 DETIK`},
{title: `22 DETIK`, rowId: `${prefix + command} seconds ${toMs("22seconds")}`, description: `${command.toUpperCase()} 22 DETIK`},
{title: `23 DETIK`, rowId: `${prefix + command} seconds ${toMs("23seconds")}`, description: `${command.toUpperCase()} 23 DETIK`},
{title: `24 DETIK`, rowId: `${prefix + command} seconds ${toMs("24seconds")}`, description: `${command.toUpperCase()} 24 DETIK`},
{title: `25 DETIK`, rowId: `${prefix + command} seconds ${toMs("25seconds")}`, description: `${command.toUpperCase()} 25 DETIK`},
{title: `26 DETIK`, rowId: `${prefix + command} seconds ${toMs("26seconds")}`, description: `${command.toUpperCase()} 26 DETIK`},
{title: `27 DETIK`, rowId: `${prefix + command} seconds ${toMs("27seconds")}`, description: `${command.toUpperCase()} 27 DETIK`},
{title: `28 DETIK`, rowId: `${prefix + command} seconds ${toMs("28seconds")}`, description: `${command.toUpperCase()} 28 DETIK`},
{title: `29 DETIK`, rowId: `${prefix + command} seconds ${toMs("29seconds")}`, description: `${command.toUpperCase()} 29 DETIK`},
{title: `30 DETIK`, rowId: `${prefix + command} seconds ${toMs("30seconds")}`, description: `${command.toUpperCase()} 30 DETIK`},
{title: `31 DETIK`, rowId: `${prefix + command} seconds ${toMs("31seconds")}`, description: `${command.toUpperCase()} 31 DETIK`},
{title: `32 DETIK`, rowId: `${prefix + command} seconds ${toMs("32seconds")}`, description: `${command.toUpperCase()} 32 DETIK`},
{title: `33 DETIK`, rowId: `${prefix + command} seconds ${toMs("33seconds")}`, description: `${command.toUpperCase()} 33 DETIK`},
{title: `34 DETIK`, rowId: `${prefix + command} seconds ${toMs("34seconds")}`, description: `${command.toUpperCase()} 34 DETIK`},
{title: `35 DETIK`, rowId: `${prefix + command} seconds ${toMs("35seconds")}`, description: `${command.toUpperCase()} 35 DETIK`},
{title: `36 DETIK`, rowId: `${prefix + command} seconds ${toMs("36seconds")}`, description: `${command.toUpperCase()} 36 DETIK`},
{title: `37 DETIK`, rowId: `${prefix + command} seconds ${toMs("37seconds")}`, description: `${command.toUpperCase()} 37 DETIK`},
{title: `38 DETIK`, rowId: `${prefix + command} seconds ${toMs("38seconds")}`, description: `${command.toUpperCase()} 38 DETIK`},
{title: `39 DETIK`, rowId: `${prefix + command} seconds ${toMs("39seconds")}`, description: `${command.toUpperCase()} 39 DETIK`},
{title: `40 DETIK`, rowId: `${prefix + command} seconds ${toMs("40seconds")}`, description: `${command.toUpperCase()} 40 DETIK`},
{title: `41 DETIK`, rowId: `${prefix + command} seconds ${toMs("41seconds")}`, description: `${command.toUpperCase()} 41 DETIK`},
{title: `42 DETIK`, rowId: `${prefix + command} seconds ${toMs("42seconds")}`, description: `${command.toUpperCase()} 42 DETIK`},
{title: `43 DETIK`, rowId: `${prefix + command} seconds ${toMs("43seconds")}`, description: `${command.toUpperCase()} 43 DETIK`},
{title: `44 DETIK`, rowId: `${prefix + command} seconds ${toMs("44seconds")}`, description: `${command.toUpperCase()} 44 DETIK`},
{title: `45 DETIK`, rowId: `${prefix + command} seconds ${toMs("45seconds")}`, description: `${command.toUpperCase()} 45 DETIK`},
{title: `46 DETIK`, rowId: `${prefix + command} seconds ${toMs("46seconds")}`, description: `${command.toUpperCase()} 46 DETIK`},
{title: `47 DETIK`, rowId: `${prefix + command} seconds ${toMs("47seconds")}`, description: `${command.toUpperCase()} 47 DETIK`},
{title: `48 DETIK`, rowId: `${prefix + command} seconds ${toMs("48seconds")}`, description: `${command.toUpperCase()} 48 DETIK`},
{title: `49 DETIK`, rowId: `${prefix + command} seconds ${toMs("49seconds")}`, description: `${command.toUpperCase()} 49 DETIK`},
{title: `50 DETIK`, rowId: `${prefix + command} seconds ${toMs("50seconds")}`, description: `${command.toUpperCase()} 50 DETIK`},
{title: `51 DETIK`, rowId: `${prefix + command} seconds ${toMs("51seconds")}`, description: `${command.toUpperCase()} 51 DETIK`},
{title: `52 DETIK`, rowId: `${prefix + command} seconds ${toMs("52seconds")}`, description: `${command.toUpperCase()} 52 DETIK`},
{title: `53 DETIK`, rowId: `${prefix + command} seconds ${toMs("53seconds")}`, description: `${command.toUpperCase()} 53 DETIK`},
{title: `54 DETIK`, rowId: `${prefix + command} seconds ${toMs("54seconds")}`, description: `${command.toUpperCase()} 54 DETIK`},
{title: `55 DETIK`, rowId: `${prefix + command} seconds ${toMs("55seconds")}`, description: `${command.toUpperCase()} 55 DETIK`},
{title: `56 DETIK`, rowId: `${prefix + command} seconds ${toMs("56seconds")}`, description: `${command.toUpperCase()} 56 DETIK`},
{title: `57 DETIK`, rowId: `${prefix + command} seconds ${toMs("57seconds")}`, description: `${command.toUpperCase()} 57 DETIK`},
{title: `58 DETIK`, rowId: `${prefix + command} seconds ${toMs("58seconds")}`, description: `${command.toUpperCase()} 58 DETIK`},
{title: `59 DETIK`, rowId: `${prefix + command} seconds ${toMs("59seconds")}`, description: `${command.toUpperCase()} 59 DETIK`},
{title: `60 DETIK`, rowId: `${prefix + command} seconds ${toMs("60seconds")}`, description: `${command.toUpperCase()} 60 DETIK`},
]}]
const listMessage = { text: `${command.toUpperCase()} DETIK`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
}