module.exports = async(sock, m, prefix, command, text) => {
if (text.split('|')[0] && text.split('|')[1] == `seconds`) {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|1`, description: `ADD OWNER 1 SECONDS`},
{title: `2 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|2`, description: `ADD OWNER 2 SECONDS`},
{title: `3 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|3`, description: `ADD OWNER 3 SECONDS`},
{title: `4 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|4`, description: `ADD OWNER 4 SECONDS`},
{title: `5 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|5`, description: `ADD OWNER 5 SECONDS`},
{title: `6 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|6`, description: `ADD OWNER 6 SECONDS`},
{title: `7 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|7`, description: `ADD OWNER 7 SECONDS`},
{title: `8 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|8`, description: `ADD OWNER 8 SECONDS`},
{title: `9 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|9`, description: `ADD OWNER 9 SECONDS`},
{title: `10 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|10`, description: `ADD OWNER 10 SECONDS`},
{title: `11 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|11`, description: `ADD OWNER 11 SECONDS`},
{title: `12 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|12`, description: `ADD OWNER 12 SECONDS`},
{title: `13 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|13`, description: `ADD OWNER 13 SECONDS`},
{title: `14 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|14`, description: `ADD OWNER 14 SECONDS`},
{title: `15 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|15`, description: `ADD OWNER 15 SECONDS`},
{title: `16 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|16`, description: `ADD OWNER 16 SECONDS`},
{title: `17 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|17`, description: `ADD OWNER 17 SECONDS`},
{title: `18 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|18`, description: `ADD OWNER 18 SECONDS`},
{title: `19 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|19`, description: `ADD OWNER 19 SECONDS`},
{title: `20 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|20`, description: `ADD OWNER 20 SECONDS`},
{title: `21 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|21`, description: `ADD OWNER 21 SECONDS`},
{title: `22 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|22`, description: `ADD OWNER 22 SECONDS`},
{title: `23 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|23`, description: `ADD OWNER 23 SECONDS`},
{title: `24 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|24`, description: `ADD OWNER 24 SECONDS`},
{title: `25 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|25`, description: `ADD OWNER 25 SECONDS`},
{title: `26 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|26`, description: `ADD OWNER 26 SECONDS`},
{title: `27 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|27`, description: `ADD OWNER 27 SECONDS`},
{title: `28 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|28`, description: `ADD OWNER 28 SECONDS`},
{title: `29 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|29`, description: `ADD OWNER 29 SECONDS`},
{title: `30 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|30`, description: `ADD OWNER 30 SECONDS`},
{title: `31 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|31`, description: `ADD OWNER 31 SECONDS`},
{title: `32 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|32`, description: `ADD OWNER 32 SECONDS`},
{title: `33 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|33`, description: `ADD OWNER 33 SECONDS`},
{title: `34 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|34`, description: `ADD OWNER 34 SECONDS`},
{title: `35 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|35`, description: `ADD OWNER 35 SECONDS`},
{title: `36 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|36`, description: `ADD OWNER 36 SECONDS`},
{title: `37 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|37`, description: `ADD OWNER 37 SECONDS`},
{title: `38 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|38`, description: `ADD OWNER 38 SECONDS`},
{title: `39 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|39`, description: `ADD OWNER 39 SECONDS`},
{title: `40 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|40`, description: `ADD OWNER 40 SECONDS`},
{title: `41 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|41`, description: `ADD OWNER 41 SECONDS`},
{title: `42 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|42`, description: `ADD OWNER 42 SECONDS`},
{title: `43 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|43`, description: `ADD OWNER 43 SECONDS`},
{title: `44 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|44`, description: `ADD OWNER 44 SECONDS`},
{title: `45 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|45`, description: `ADD OWNER 45 SECONDS`},
{title: `46 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|46`, description: `ADD OWNER 46 SECONDS`},
{title: `47 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|47`, description: `ADD OWNER 47 SECONDS`},
{title: `48 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|48`, description: `ADD OWNER 48 SECONDS`},
{title: `49 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|49`, description: `ADD OWNER 49 SECONDS`},
{title: `50 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|50`, description: `ADD OWNER 50 SECONDS`},
{title: `51 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|51`, description: `ADD OWNER 51 SECONDS`},
{title: `52 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|52`, description: `ADD OWNER 52 SECONDS`},
{title: `53 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|53`, description: `ADD OWNER 53 SECONDS`},
{title: `54 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|54`, description: `ADD OWNER 54 SECONDS`},
{title: `55 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|55`, description: `ADD OWNER 55 SECONDS`},
{title: `56 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|56`, description: `ADD OWNER 56 SECONDS`},
{title: `57 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|57`, description: `ADD OWNER 57 SECONDS`},
{title: `58 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|58`, description: `ADD OWNER 58 SECONDS`},
{title: `59 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|59`, description: `ADD OWNER 59 SECONDS`},
{title: `60 SECONDS`, rowId: `${prefix + command} ${text.split('|')[0]}|seconds|60`, description: `ADD OWNER 60 SECONDS`},
]}]
const listMessage = { text: `ADD OWNER ${text.split('|')[1].toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
} else if (text.split('|')[0] && text.split('|')[1] == `minutes`) {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|1`, description: `ADD OWNER 1 MINUTES`},
{title: `2 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|2`, description: `ADD OWNER 2 MINUTES`},
{title: `3 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|3`, description: `ADD OWNER 3 MINUTES`},
{title: `4 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|4`, description: `ADD OWNER 4 MINUTES`},
{title: `5 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|5`, description: `ADD OWNER 5 MINUTES`},
{title: `6 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|6`, description: `ADD OWNER 6 MINUTES`},
{title: `7 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|7`, description: `ADD OWNER 7 MINUTES`},
{title: `8 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|8`, description: `ADD OWNER 8 MINUTES`},
{title: `9 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|9`, description: `ADD OWNER 9 MINUTES`},
{title: `10 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|10`, description: `ADD OWNER 10 MINUTES`},
{title: `11 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|11`, description: `ADD OWNER 11 MINUTES`},
{title: `12 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|12`, description: `ADD OWNER 12 MINUTES`},
{title: `13 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|13`, description: `ADD OWNER 13 MINUTES`},
{title: `14 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|14`, description: `ADD OWNER 14 MINUTES`},
{title: `15 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|15`, description: `ADD OWNER 15 MINUTES`},
{title: `16 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|16`, description: `ADD OWNER 16 MINUTES`},
{title: `17 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|17`, description: `ADD OWNER 17 MINUTES`},
{title: `18 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|18`, description: `ADD OWNER 18 MINUTES`},
{title: `19 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|19`, description: `ADD OWNER 19 MINUTES`},
{title: `20 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|20`, description: `ADD OWNER 20 MINUTES`},
{title: `21 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|21`, description: `ADD OWNER 21 MINUTES`},
{title: `22 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|22`, description: `ADD OWNER 22 MINUTES`},
{title: `23 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|23`, description: `ADD OWNER 23 MINUTES`},
{title: `24 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|24`, description: `ADD OWNER 24 MINUTES`},
{title: `25 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|25`, description: `ADD OWNER 25 MINUTES`},
{title: `26 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|26`, description: `ADD OWNER 26 MINUTES`},
{title: `27 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|27`, description: `ADD OWNER 27 MINUTES`},
{title: `28 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|28`, description: `ADD OWNER 28 MINUTES`},
{title: `29 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|29`, description: `ADD OWNER 29 MINUTES`},
{title: `30 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|30`, description: `ADD OWNER 30 MINUTES`},
{title: `31 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|31`, description: `ADD OWNER 31 MINUTES`},
{title: `32 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|32`, description: `ADD OWNER 32 MINUTES`},
{title: `33 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|33`, description: `ADD OWNER 33 MINUTES`},
{title: `34 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|34`, description: `ADD OWNER 34 MINUTES`},
{title: `35 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|35`, description: `ADD OWNER 35 MINUTES`},
{title: `36 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|36`, description: `ADD OWNER 36 MINUTES`},
{title: `37 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|37`, description: `ADD OWNER 37 MINUTES`},
{title: `38 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|38`, description: `ADD OWNER 38 MINUTES`},
{title: `39 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|39`, description: `ADD OWNER 39 MINUTES`},
{title: `40 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|40`, description: `ADD OWNER 40 MINUTES`},
{title: `41 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|41`, description: `ADD OWNER 41 MINUTES`},
{title: `42 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|42`, description: `ADD OWNER 42 MINUTES`},
{title: `43 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|43`, description: `ADD OWNER 43 MINUTES`},
{title: `44 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|44`, description: `ADD OWNER 44 MINUTES`},
{title: `45 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|45`, description: `ADD OWNER 45 MINUTES`},
{title: `46 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|46`, description: `ADD OWNER 46 MINUTES`},
{title: `47 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|47`, description: `ADD OWNER 47 MINUTES`},
{title: `48 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|48`, description: `ADD OWNER 48 MINUTES`},
{title: `49 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|49`, description: `ADD OWNER 49 MINUTES`},
{title: `50 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|50`, description: `ADD OWNER 50 MINUTES`},
{title: `51 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|51`, description: `ADD OWNER 51 MINUTES`},
{title: `52 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|52`, description: `ADD OWNER 52 MINUTES`},
{title: `53 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|53`, description: `ADD OWNER 53 MINUTES`},
{title: `54 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|54`, description: `ADD OWNER 54 MINUTES`},
{title: `55 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|55`, description: `ADD OWNER 55 MINUTES`},
{title: `56 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|56`, description: `ADD OWNER 56 MINUTES`},
{title: `57 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|57`, description: `ADD OWNER 57 MINUTES`},
{title: `58 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|58`, description: `ADD OWNER 58 MINUTES`},
{title: `59 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|59`, description: `ADD OWNER 59 MINUTES`},
{title: `60 MINUTES`, rowId: `${prefix + command} ${text.split('|')[0]}|minutes|60`, description: `ADD OWNER 60 MINUTES`},
]}]
const listMessage = { text: `ADD OWNER ${text.split('|')[1].toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
} else if (text.split('|')[0] && text.split('|')[1] == `hours`) {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|1`, description: `ADD OWNER 1 HOURS`},
{title: `2 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|2`, description: `ADD OWNER 2 HOURS`},
{title: `3 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|3`, description: `ADD OWNER 3 HOURS`},
{title: `4 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|4`, description: `ADD OWNER 4 HOURS`},
{title: `5 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|5`, description: `ADD OWNER 5 HOURS`},
{title: `6 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|6`, description: `ADD OWNER 6 HOURS`},
{title: `7 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|7`, description: `ADD OWNER 7 HOURS`},
{title: `8 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|8`, description: `ADD OWNER 8 HOURS`},
{title: `9 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|9`, description: `ADD OWNER 9 HOURS`},
{title: `10 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|10`, description: `ADD OWNER 10 HOURS`},
{title: `11 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|11`, description: `ADD OWNER 11 HOURS`},
{title: `12 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|12`, description: `ADD OWNER 12 HOURS`},
{title: `13 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|13`, description: `ADD OWNER 13 HOURS`},
{title: `14 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|14`, description: `ADD OWNER 14 HOURS`},
{title: `15 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|15`, description: `ADD OWNER 15 HOURS`},
{title: `16 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|16`, description: `ADD OWNER 16 HOURS`},
{title: `17 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|17`, description: `ADD OWNER 17 HOURS`},
{title: `18 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|18`, description: `ADD OWNER 18 HOURS`},
{title: `19 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|19`, description: `ADD OWNER 19 HOURS`},
{title: `20 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|20`, description: `ADD OWNER 20 HOURS`},
{title: `21 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|21`, description: `ADD OWNER 21 HOURS`},
{title: `22 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|22`, description: `ADD OWNER 22 HOURS`},
{title: `23 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|23`, description: `ADD OWNER 23 HOURS`},
{title: `24 HOURS`, rowId: `${prefix + command} ${text.split('|')[0]}|hours|24`, description: `ADD OWNER 24 HOURS`},
]}]
const listMessage = { text: `ADD OWNER ${text.split('|')[1].toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
} else if (text.split('|')[0] && text.split('|')[1] == `days`) {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|1`, description: `ADD OWNER 1 DAYS`},
{title: `2 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|2`, description: `ADD OWNER 2 DAYS`},
{title: `3 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|3`, description: `ADD OWNER 3 DAYS`},
{title: `4 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|4`, description: `ADD OWNER 4 DAYS`},
{title: `5 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|5`, description: `ADD OWNER 5 DAYS`},
{title: `6 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|6`, description: `ADD OWNER 6 DAYS`},
{title: `7 DAYS`, rowId: `${prefix + command} ${text.split('|')[0]}|days|7`, description: `ADD OWNER 7 DAYS`},
]}]
const listMessage = { text: `ADD OWNER ${text.split('|')[1].toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
} else if (text.split('|')[0] && text.split('|')[1] == `weeks`) {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 WEEKS`, rowId: `${prefix + command} ${text.split('|')[0]}|weeks|1`, description: `ADD OWNER 1 WEEKS`},
{title: `2 WEEKS`, rowId: `${prefix + command} ${text.split('|')[0]}|weeks|2`, description: `ADD OWNER 2 WEEKS`},
{title: `3 WEEKS`, rowId: `${prefix + command} ${text.split('|')[0]}|weeks|3`, description: `ADD OWNER 3 WEEKS`},
{title: `4 WEEKS`, rowId: `${prefix + command} ${text.split('|')[0]}|weeks|4`, description: `ADD OWNER 4 WEEKS`},
]}]
const listMessage = { text: `ADD OWNER ${text.split('|')[1].toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
} else if (text.split('|')[0] && text.split('|')[1] == `months`) {
const sections = [ {
title: `PLEASE SELECT`,
rows: [
{title: `1 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|1`, description: `ADD OWNER 1 MONTHS`},
{title: `2 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|2`, description: `ADD OWNER 2 MONTHS`},
{title: `3 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|3`, description: `ADD OWNER 3 MONTHS`},
{title: `4 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|4`, description: `ADD OWNER 4 MONTHS`},
{title: `5 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|5`, description: `ADD OWNER 5 MONTHS`},
{title: `6 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|6`, description: `ADD OWNER 6 MONTHS`},
{title: `7 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|7`, description: `ADD OWNER 7 MONTHS`},
{title: `8 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|8`, description: `ADD OWNER 8 MONTHS`},
{title: `9 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|9`, description: `ADD OWNER 9 MONTHS`},
{title: `10 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|10`, description: `ADD OWNER 10 MONTHS`},
{title: `11 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|11`, description: `ADD OWNER 11 MONTHS`},
{title: `12 MONTHS`, rowId: `${prefix + command} ${text.split('|')[0]}|months|12`, description: `ADD OWNER 12 MONTHS`},
]}]
const listMessage = { text: `ADD OWNER ${text.split('|')[1].toUpperCase()}`, buttonText: `Click Here`, sections }
sock.sendMessage(m.chat, listMessage, { quoted: m })
}
}